### ISSUE TITLE
debian and centos version of jenkins-slave

### ISSUE THREAD

**Issue by arthurzenika** [evarga/docker-images#10]
We are using the docker-plugin with jenkins but we test/build against debian and centos

Would you like some contributions of docker files for those distros ?

**Comment by evarga** [comment]
Hi Arthur,

Sure, those additional variants may be put inside a separate branch (the master containes the current variant), and I would attach separate Docker image tags to them.

Thanks,
Ervin

**Comment by evarga** [comment]
The repository has been archived, so no more work will happen in it.
